version: '3'
services:
  web:
    container_name: web
    build: .
    command: bash -c "npm run migrate && npm run start:dev" # to run pending migrations and run server using nodemon for development
    ports:
      - 4040:8080
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://nimesh:nimesh@postgres/postgres
    volumes:
      - ./src:/usr/src/app/src # to mount local volume for development
      - ./config:/usr/src/app/config # to mount local volume for development
  postgres:
    container_name: postgres
    image: postgres:9.6.2-alpine
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: nimesh
      POSTGRES_PASSWORD: nimesh
      POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql