version: '3'
services:
  web:
    container_name: web
    build: .
    command: npm start
    ports:
      - 4040:8080
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://nimesh@postgres/nimesh
  postgres:
    container_name: postgres
    image: postgres:9.6.2-alpine
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: nimesh
      POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql